# This workflow will build java project with Gradlew

name: Java CI with Gradle

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
jobs:
  build:
   
   runs-on: ubuntu-latest
   
   steps:
   - name: Checkout repository
     uses: actions/checkout@v3
    
    
